title: 15418 Final Project
description: A comprehensive comparison of parallel and distributed B+ trees
show_downloads: false
theme: jekyll-theme-cayman
baseurl: /15-418-Final-Project

github:
  is_project_page: true
  repository_url: https://github.com/MarkChenYutian/15-418-Final-Project
  repository_name: 15418 Final Project
  owner_url: https://github.com/MarkChenYutian
  owner_name: Yutian Chen
